### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by dcaswel** [lemonstand/omnipay-beanstream#5]
Can you please create a new release so we can import the new functions into our system? If you are not able to create a release, please let me know what needs to be done so you can. Thanks!!

**Comment by dcaswel** [comment]
I'm sorry to get pushy on this but I really need to be able to integrate this into our project but I can't do that without a stable release. I would really appreciate if you could create a new release for me. I don't want to do this but it is coming close to the point that I am going to have to re-release it under my account so I can move forward with the project. Thank you!

**Comment by aperdomo** [comment]
@caswell-wc 

I'll get a release set up for you.

**Comment by aperdomo** [comment]
@caswell-wc 

See: https://packagist.org/packages/lemonstand/omnipay-beanstream#v1.1.0
